name: Instagram Bot

on:
  schedule:
    # Menjadwalkan untuk menjalankan bot setiap menit
    - cron: '*/1 * * * *'  # Menjalankan setiap menit
  push:
    branches:
      - main  # Jika ada perubahan di branch main, bot akan dijalankan

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Instagram Bot
      run: |
        python bot.py
        
